name: deploy_static_site

on:
  workflow_dispatch:       # allow running manually

jobs:
  deploy_static_site:
  	name: Deploy Static Site
    runs-on: ubuntu-latest
    steps:
      - name: Creates static site
        uses: actions/checkout@v2
        run:  sh ./build_static_site.sh # some command from your repository that creates
                            			# output to "source-directory"
      - name: Pushes to the static site repository
        uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '_site'
          destination-github-username: 'emmajuettner'
          destination-repository-name: 'emmajuettner.github.io'
          user-email: 22248856+emmajuettner@users.noreply.github.com
          target-branch: master
